"""Definicao das metricas do dashboard e instrucoes de coleta.

Cada metrica mapeia uma secao do Painel Estrategico Territorial
para uma tabela e expressao SQL no BigQuery.
"""

PROJETO = "br-mec-segape-dev"
SCHEMA = f"{PROJETO}.projeto_painel_ministro"

METRICAS: list[dict] = [
    # === Pagina 1 - Educacao Basica I ===
    {
        "pagina": "1 - Educacao Basica I",
        "secao": "Escolas",
        "query": "painel_escola",
        "gcp": f"{SCHEMA}.painel_escola",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_estado": "estado",
        "coluna_ano": None,
        "expressao": "SUM(quantidade_escola)",
        "nome_metrica": "Escolas",
    },
    {
        "pagina": "1 - Educacao Basica I",
        "secao": "Escolas",
        "query": "painel_escola",
        "gcp": f"{SCHEMA}.painel_escola",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(quantidade_escola_integral)",
        "nome_metrica": "Escolas Integrais",
    },
    {
        "pagina": "1 - Educacao Basica I",
        "secao": "Matriculas",
        "query": "painel_matricula_municipio",
        "gcp": f"{SCHEMA}.painel_matricula_municipio",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(quantidade_matricula)",
        "nome_metrica": "Matriculas Total",
    },
    {
        "pagina": "1 - Educacao Basica I",
        "secao": "Docentes e Infraestrutura",
        "query": "painel_pneerq_infraestrutura_escolar",
        "gcp": f"{SCHEMA}.painel_pneerq_infraestrutura_escolar",
        "status_modelo": "ativo",
        "coluna_municipio": "nome_municipio",
        "formato_municipio": "cidade",
        "coluna_estado": "sigla_uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "SUM(CASE WHEN rede IN ('Municipal', 'Estadual', 'Federal') THEN quantidade_docente_educacao_basica ELSE 0 END)",
        "nome_metrica": "Docentes Educacao Basica (Publica)",
    },
    {
        "pagina": "1 - Educacao Basica I",
        "secao": "Infraestrutura PNEERQ",
        "query": "painel_pneerq_infraestrutura_escolar",
        "gcp": f"{SCHEMA}.painel_pneerq_infraestrutura_escolar",
        "status_modelo": "ativo",
        "coluna_municipio": "nome_municipio",
        "formato_municipio": "cidade",
        "coluna_estado": "sigla_uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "COUNT(DISTINCT id_escola)",
        "nome_metrica": "Escolas PNEERQ",
    },
    {
        "pagina": "1 - Educacao Basica I",
        "secao": "Infraestrutura PNEERQ",
        "query": "painel_pneerq_infraestrutura_escolar",
        "gcp": f"{SCHEMA}.painel_pneerq_infraestrutura_escolar",
        "status_modelo": "ativo",
        "coluna_municipio": "nome_municipio",
        "formato_municipio": "cidade",
        "coluna_estado": "sigla_uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "SUM(quantidade_matricula_educacao_basica)",
        "nome_metrica": "Matriculas Educacao Basica (PNEERQ)",
    },
    {
        "pagina": "1 - Educacao Basica I",
        "secao": "Infraestrutura Quilombolas",
        "query": "painel_pneerq_infraestrutura_escolar",
        "gcp": f"{SCHEMA}.painel_pneerq_infraestrutura_escolar",
        "status_modelo": "ativo",
        "coluna_municipio": "nome_municipio",
        "formato_municipio": "cidade",
        "coluna_estado": "sigla_uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "COUNT(DISTINCT CASE WHEN localizacao_diferenciada = 'Quilombolas' THEN id_escola END)",
        "nome_metrica": "Escolas Quilombolas",
    },
    # === Pagina 3 - Educacao Basica III ===
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "CNCA",
        "query": "painel_cnca",
        "gcp": f"{SCHEMA}.painel_cnca",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(valor_pago_total)",
        "nome_metrica": "CNCA Investimento Total",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "CNCA",
        "query": "painel_cnca",
        "gcp": f"{SCHEMA}.painel_cnca",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(valor_repasse_bolsistas_total)",
        "nome_metrica": "CNCA Repasse Bolsistas",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "CNCA",
        "query": "painel_cnca",
        "gcp": f"{SCHEMA}.painel_cnca",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(valor_pago_formacoes)",
        "nome_metrica": "CNCA Formacoes Pagas",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "CNCA",
        "query": "painel_cnca",
        "gcp": f"{SCHEMA}.painel_cnca",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(valor_empenhado_formacoes)",
        "nome_metrica": "CNCA Formacoes Empenhadas",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "CNCA",
        "query": "painel_cnca",
        "gcp": f"{SCHEMA}.painel_cnca",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "MAX(qtd_articuladores_total)",
        "nome_metrica": "CNCA Articuladores Total",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "CNCA Investimento",
        "query": "painel_cnca_investimento",
        "gcp": f"{SCHEMA}.painel_cnca_investimento",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "IFNULL(SUM(valor_pago_total),0) + IFNULL(SUM(valor_pago_leei_2024),0) + IFNULL(SUM(valor_pago_leei_2025_2026),0)",
        "nome_metrica": "CNCA Investimento Acumulado",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "Mais Professores (PND)",
        "query": "painel_pnd_adesao",
        "gcp": f"{SCHEMA}.painel_pnd_adesao",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "COUNT(DISTINCT CASE WHEN submissao = TRUE AND indicador_uf = FALSE THEN id_ibge END)",
        "nome_metrica": "PND Municipios Aderidos",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "Mais Professores (PND)",
        "query": "painel_pnd_adesao",
        "gcp": f"{SCHEMA}.painel_pnd_adesao",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "COUNT(DISTINCT CASE WHEN submissao = TRUE AND indicador_uf = TRUE THEN id_ibge END)",
        "nome_metrica": "PND Estados Aderidos",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "Pe-de-Meia Licenciaturas",
        "query": "painel_pdmlic",
        "gcp": f"{SCHEMA}.painel_pdmlic",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano",
        "expressao": "COUNTIF(elegivel = TRUE)",
        "nome_metrica": "PDMLIC Elegiveis",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "Pe-de-Meia Licenciaturas",
        "query": "painel_pdmlic",
        "gcp": f"{SCHEMA}.painel_pdmlic",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano",
        "expressao": "COUNTIF(cadastrado = TRUE)",
        "nome_metrica": "PDMLIC Cadastrados",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "Pe-de-Meia Licenciaturas",
        "query": "painel_pdmlic",
        "gcp": f"{SCHEMA}.painel_pdmlic",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano",
        "expressao": "COUNTIF(beneficiario = TRUE)",
        "nome_metrica": "PDMLIC Beneficiarios",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "ETI",
        "query": "eti_valores_2025_csv",
        "gcp": f"{PROJETO}.andre_teste.eti_valores_2025_csv",
        "status_modelo": "externo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade",
        "coluna_estado": "uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "SUM(CAST(valor_repasse AS FLOAT64))",
        "nome_metrica": "ETI Valor Repasse",
    },
    {
        "pagina": "3 - Educacao Basica III",
        "secao": "ETI",
        "query": "eti_valores_2025_csv",
        "gcp": f"{PROJETO}.andre_teste.eti_valores_2025_csv",
        "status_modelo": "externo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade",
        "coluna_estado": "uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "SUM(CAST(valor_total_fomento AS FLOAT64))",
        "nome_metrica": "ETI Valor Fomento",
    },
    # === Pagina 4 - Financiamentos ===
    {
        "pagina": "4 - Financiamentos",
        "secao": "FUNDEB",
        "query": "painel_fundeb",
        "gcp": f"{SCHEMA}.painel_fundeb",
        "status_modelo": "ativo",
        "coluna_municipio": "nome_municipio",
        "formato_municipio": "CIDADE",
        "coluna_estado": "uf",
        "filtro_por_id": True,
        "filtro_extra": "status = 'Realizado'",
        "coluna_ano": "ano",
        "expressao": "SUM(repasse)",
        "nome_metrica": "FUNDEB Repasse (Realizado)",
    },
    {
        "pagina": "4 - Financiamentos",
        "secao": "Salario Educacao",
        "query": "painel_salario_educacao",
        "gcp": f"{SCHEMA}.painel_salario_educacao",
        "status_modelo": "ativo",
        "coluna_municipio": "nome_municipio",
        "formato_municipio": "CIDADE",
        "coluna_estado": "uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "SUM(CASE WHEN id_status = 1 THEN repasse ELSE 0 END)",
        "nome_metrica": "Salario Educacao Repasse (Realizado)",
    },
    # === Pagina 5 - EPT / Superior ===
    {
        "pagina": "5 - EPT / Superior",
        "secao": "SISTEC",
        "query": "painel_ept_sistec",
        "gcp": f"{SCHEMA}.painel_ept_sistec",
        "status_modelo": "ativo",
        "coluna_municipio": "nome_municipio",
        "formato_municipio": "cidade",
        "coluna_estado": "sigla_uf",
        "filtro_por_id": True,
        "coluna_ano": "ano",
        "expressao": "SUM(quantidade_matricula)",
        "nome_metrica": "SISTEC Matriculas",
    },
    {
        "pagina": "5 - EPT / Superior",
        "secao": "Pronatec",
        "query": "painel_pronatec_completo",
        "gcp": f"{SCHEMA}.painel_pronatec_completo",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano",
        "expressao": "SUM(CASE WHEN tipo_vinculo = 'Vagas' THEN quantidade ELSE 0 END)",
        "nome_metrica": "Pronatec Vagas",
    },
    {
        "pagina": "5 - EPT / Superior",
        "secao": "Pronatec",
        "query": "painel_pronatec_completo",
        "gcp": f"{SCHEMA}.painel_pronatec_completo",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano",
        "expressao": "SUM(CASE WHEN tipo_vinculo = 'Matriculas' THEN quantidade ELSE 0 END)",
        "nome_metrica": "Pronatec Matriculas",
    },
    {
        "pagina": "5 - EPT / Superior",
        "secao": "Mulheres Mil",
        "query": "painel_mulheresmil_completo",
        "gcp": f"{SCHEMA}.painel_mulheresmil_completo",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano",
        "expressao": "SUM(quantidade)",
        "nome_metrica": "Mulheres Mil Total",
    },
    {
        "pagina": "5 - EPT / Superior",
        "secao": "SISU",
        "query": "painel_sisu",
        "gcp": f"{SCHEMA}.painel_sisu",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano_tratado",
        "expressao": "SUM(qtd_vagas_ofertadas)",
        "nome_metrica": "SISU Vagas Ofertadas",
    },
    {
        "pagina": "5 - EPT / Superior",
        "secao": "FIES",
        "query": "painel_fnde_fies_investimento",
        "gcp": f"{SCHEMA}.painel_fnde_fies_investimento",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": "ano_tratado",
        "expressao": "SUM(valor_pago)",
        "nome_metrica": "FIES Valor Pago",
    },
    # === Pagina 6 - Novo PAC ===
    {
        "pagina": "6 - Novo PAC",
        "secao": "Consolidado",
        "query": "painel_novopac_consolidado",
        "gcp": f"{SCHEMA}.painel_novopac_consolidado",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "COUNT(DISTINCT id_governa)",
        "nome_metrica": "Novo PAC Total Acoes",
    },
    {
        "pagina": "6 - Novo PAC",
        "secao": "Consolidado",
        "query": "painel_novopac_consolidado",
        "gcp": f"{SCHEMA}.painel_novopac_consolidado",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(CASE WHEN id_governa IS NOT NULL THEN valor_previsto ELSE 0 END)",
        "nome_metrica": "Novo PAC Valor Previsto",
    },
    {
        "pagina": "6 - Novo PAC",
        "secao": "Selecoes",
        "query": "painel_novopac_selecoes_consolidado",
        "gcp": f"{SCHEMA}.painel_novopac_selecoes_consolidado",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio_obra",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "COUNT(DISTINCT proposta)",
        "nome_metrica": "Selecoes Total",
    },
    {
        "pagina": "6 - Novo PAC",
        "secao": "Selecoes",
        "query": "painel_novopac_selecoes_consolidado",
        "gcp": f"{SCHEMA}.painel_novopac_selecoes_consolidado",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio_obra",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "MAX(valor_investimento)",
        "nome_metrica": "Selecoes Valor Investimento",
    },
    {
        "pagina": "6 - Novo PAC",
        "secao": "Pacto Retomada",
        "query": "painel_novopac_pacto",
        "gcp": f"{SCHEMA}.painel_novopac_pacto",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio_obra",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "COUNT(DISTINCT id_obra)",
        "nome_metrica": "Pacto Total Obras",
    },
    {
        "pagina": "6 - Novo PAC",
        "secao": "Pacto Retomada",
        "query": "painel_novopac_pacto",
        "gcp": f"{SCHEMA}.painel_novopac_pacto",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio_obra",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(valor_previsto)",
        "nome_metrica": "Pacto Valor Previsto",
    },
    {
        "pagina": "6 - Novo PAC",
        "secao": "SESU Universidades",
        "query": "painel_novopac_sesu",
        "gcp": f"{SCHEMA}.painel_novopac_sesu",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio_obra",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "COUNT(DISTINCT id_governa)",
        "nome_metrica": "SESU Total Obras",
    },
    {
        "pagina": "6 - Novo PAC",
        "secao": "SESU Universidades",
        "query": "painel_novopac_sesu",
        "gcp": f"{SCHEMA}.painel_novopac_sesu",
        "status_modelo": "ativo",
        "coluna_municipio": "municipio_obra",
        "formato_municipio": "cidade - UF",
        "coluna_ano": None,
        "expressao": "SUM(valor_previsto)",
        "nome_metrica": "SESU Valor Previsto",
    },
]


INSTRUCOES_DASHBOARD: dict[str, str] = {
    "Escolas": "Pag.1 > card 'Escolas'. Esfera: Todas.",
    "Escolas Integrais": "Pag.1 > filtro integral se existir.",
    "Matriculas Total": "Pag.1 > card 'Matriculas' (8.897 no PDF). Esfera: Todas.",
    "Docentes Educacao Basica (Publica)": (
        "Pag.1 > card 'Docentes*' (519 no PDF). "
        "Dashboard usa COUNT DISTINCT (deduplica entre escolas). "
        "Nosso valor sera SUM por escola (sempre maior)."
    ),
    "Escolas PNEERQ": "Pag.1 > 'Infraestrutura nas Escolas'. Total de escolas.",
    "Matriculas Educacao Basica (PNEERQ)": "Pag.1 > tabela 'Matriculas por Etapa' > 'Total geral'.",
    "Escolas Quilombolas": "Pag.2 > secao PNEERQ > 'Escolas Quilombolas'. Se ausente: 'nao visivel'.",
    "CNCA Investimento Total": "Pag.3 > CNCA > 'Total Investido'. Soma de todos os anos.",
    "CNCA Repasse Bolsistas": "Pag.3 > CNCA > 'Repasse Articuladores Renalfa'.",
    "CNCA Formacoes Pagas": "Pag.3 > CNCA > 'Valor pago - Formacoes PAR'.",
    "CNCA Formacoes Empenhadas": "Pag.3 > CNCA > 'Valor empenhado - Formacoes PAR'.",
    "CNCA Articuladores Total": "Pag.3 > CNCA > 'Articuladores Renalfa (2025)'.",
    "CNCA Investimento Acumulado": "Pag.3 > CNCA > grafico 'Investimento por Componentes'.",
    "PND Municipios Aderidos": "Pag.3 > 'Mais Professores' > 'Municipios Aderidos'.",
    "PND Estados Aderidos": "Pag.3 > 'Mais Professores' > 'Estados Aderidos'.",
    "PDMLIC Elegiveis": "Pag.3 > 'Pe-de-Meia Licenciaturas' > 'Estudantes elegiveis'.",
    "PDMLIC Cadastrados": "Pag.3 > 'Pe-de-Meia Licenciaturas' > 'Estudantes cadastrados'.",
    "PDMLIC Beneficiarios": "Pag.3 > 'Pe-de-Meia Licenciaturas' > 'Beneficiarios'.",
    "ETI Valor Repasse": "Pag.3 > 'Escola em Tempo Integral' > valor de repasse.",
    "ETI Valor Fomento": "Pag.3 > 'Escola em Tempo Integral' > 'Total Valor Fomentado'.",
    "FUNDEB Repasse (Realizado)": "Pag.4 > FUNDEB > 'Repassado'. Filtro: Realizado.",
    "Salario Educacao Repasse (Realizado)": "Pag.4 > 'Salario Educacao' > 'Repassado'.",
    "SISTEC Matriculas": "Pag.5 > 'Qualificacao Profissional' > 'Matriculas'. Nao confundir com Nivel Medio Tecnico.",
    "Pronatec Vagas": "Pag.5 > Pronatec > 'Vagas Ofertadas'.",
    "Pronatec Matriculas": "Pag.5 > Pronatec > 'Matriculas' ou 'Cursos'.",
    "Mulheres Mil Total": "Pag.5 > 'Mulheres Mil'. Se ausente: 'nao visivel'.",
    "SISU Vagas Ofertadas": "Pag.5 > SISU > primeiro numero.",
    "FIES Valor Pago": "Pag.5 > FIES > 'R$ 0,00'. Primeiro valor e quantidade de contratos.",
    "Novo PAC Total Acoes": "Pag.6 > 'Total de Acoes'.",
    "Novo PAC Valor Previsto": "Pag.6 > 'Valor Previsto'.",
    "Selecoes Total": "Pag.6 > 'Novo PAC Selecoes' > contagem ETI.",
    "Selecoes Valor Investimento": "Pag.6 > 'Novo PAC Selecoes' > 'Valor Investimento'.",
    "Pacto Total Obras": "Pag.6 > 'Pacto Retomada' > 'Total de Obras'.",
    "Pacto Valor Previsto": "Pag.6 > 'Pacto Retomada' > 'Valor Previsto Total'.",
    "SESU Total Obras": "Pag.6 > 'Universidades Federais' > contagem.",
    "SESU Valor Previsto": "Pag.6 > 'Universidades Federais' > valor.",
}


# "Simplicidade e a sofisticacao suprema." - Leonardo da Vinci
