# -*- coding: utf-8 -*-
"""extrator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/br-mec-segape-dev/locations/southamerica-east1/repositories/e2dc08fb-3ea3-49c1-9b4d-736d81d47964

# extrator universal de documentos (pdf, docx)

este notebook permite extrair texto e tabelas de arquivos pdf e docx.

**funcionalidades:**
1.  **upload de arquivo:** envie seu arquivo (pdf, docx, etc.).
2.  **configuração de saída:** escolha como salvar as tabelas no excel.
3.  **feature a (foco em pdf):** extrai tabelas de pdfs usando `tabula-py`.
4.  **feature b (universal):** extrai texto e tabelas de `unstructured`.
5.  **feature c (pdf - empilhamento):** extrai tabelas de pdf e "empilha" continuações (lógica `pdfplumber`).

## 1. instalação das dependências

primeiro, executamos a instalação das bibliotecas necessárias.
"""

# feature b: biblioteca principal para extração de texto e layout
# (notebook) !pip install "unstructured[pdf,docx]" -q

# feature a: biblioteca especialista em extração de tabelas de pdf
# (notebook) !pip install tabula-py -q

# feature c: biblioteca alternativa para pdf e empilhamento
# (notebook) !pip install pdfplumber -q

# biblioteca para manipulação e visualização das tabelas (a, b, c)
# (notebook) !pip install pandas -q

# biblioteca necessária para o pandas escrever arquivos .xlsx (excel) (a, b, c)
# (notebook) !pip install openpyxl -q

# 'unstructured' (e 'tabula') podem precisar de ferramentas do sistema para ler pdfs
# primeiro, atualiza a lista de pacotes do sistema (corrige o erro 404 not found)
# (notebook) !sudo apt-get update -q
# agora, instala as dependências
# (notebook) !sudo apt-get install -y poppler-utils tesseract-ocr -q

"""## 2. importação das bibliotecas

agora, importamos os módulos que vamos usar.
"""

import os
import pandas as pd
import io
from google.colab import files
from IPython.display import display, HTML, Markdown

# imports da feature a
import tabula

# imports da feature b
from unstructured.partition.auto import partition
from unstructured.documents.elements import Table

# imports da feature c
import pdfplumber

print("bibliotecas carregadas com sucesso.")

"""## 3. upload do arquivo

execute a célula abaixo para selecionar o arquivo (pdf ou docx) do seu computador.
"""

uploaded = files.upload()

if not uploaded:
  print("nenhum arquivo foi enviado.")
else:
  # salva o nome do arquivo para uso posterior
  input_filepath = list(uploaded.keys())[0]
  print(f"\narquivo '{input_filepath}' carregado com sucesso.")

  # salva o arquivo em disco no ambiente do colab
  with open(input_filepath, 'wb') as f:
      f.write(uploaded[input_filepath])

"""## 4. configuração da saída

defina como as tabelas devem ser salvas no arquivo excel (apenas para features a e b).
"""

# mude para true se quiser salvar todas as tabelas em uma única aba (uma embaixo da outra)
# mude para false se quiser que cada tabela fique em sua própria aba (ex: "tabela_1", "tabela_2")
salvar_em_uma_aba = False

"""---

## feature a: extração rápida de tabelas (foco em pdf)

esta feature usa `tabula-py`, ideal para extrair tabelas de arquivos **pdf**.
"""

if 'input_filepath' not in locals() or not os.path.exists(input_filepath):
    print("erro: faça o upload de um arquivo na célula '3. upload do arquivo' primeiro.")
elif not input_filepath.lower().endswith('.pdf'):
    print(f"a feature a (tabula) funciona melhor com pdfs. pulando arquivo: {input_filepath}")
else:
    print(f"(feature a) procurando tabelas em '{input_filepath}' com tabula...")
    try:
        # tenta ler todas as tabelas de todas as páginas
        tables_tabula = tabula.read_pdf(input_filepath, pages='all', multiple_tables=True)

        if not tables_tabula:
            print("(feature a) tabula não encontrou tabelas neste pdf.")
        else:
            print(f"(feature a) encontradas {len(tables_tabula)} tabelas!")

            excel_path = 'tabelas_extraidas_tabula.xlsx'

            if salvar_em_uma_aba:
                print("(feature a) salvando todas as tabelas em uma única aba ('todas_tabelas')...")
                with pd.ExcelWriter(excel_path) as writer:
                    current_row = 0
                    for i, table_df in enumerate(tables_tabula):
                        display(Markdown(f"**tabela {i+1} (tabula)**"))
                        display(table_df)

                        # escreve o nome da tabela
                        pd.DataFrame([f"tabela {i+1}"]).to_excel(writer, sheet_name='todas_tabelas', startrow=current_row, index=False, header=False)
                        current_row += 1

                        # escreve a tabela
                        table_df.to_excel(writer, sheet_name='todas_tabelas', startrow=current_row, index=False)
                        current_row += len(table_df) + 2 # +2 para uma linha de espaço
            else:
                print("(feature a) salvando cada tabela em uma aba separada...")
                with pd.ExcelWriter(excel_path) as writer:
                    for i, table_df in enumerate(tables_tabula):
                        display(Markdown(f"**tabela {i+1} (tabula)**"))
                        display(table_df) # mostra a tabela no notebook
                        table_df.to_excel(writer, sheet_name=f'tabela_{i+1}', index=False)

            print(f"\n(feature a) tabelas salvas em '{excel_path}'.")
            # oferece o download do arquivo excel
            files.download(excel_path)

    except Exception as e:
        print(f"(feature a) ocorreu um erro ao processar o pdf com tabula: {e}")

"""---

## feature b: extração inteligente (universal - pdf, docx)

esta feature usa `unstructured` para analisar o layout do documento. funciona para **pdfs e docx**.
"""

if 'input_filepath' not in locals() or not os.path.exists(input_filepath):
    print("erro: faça o upload de um arquivo na célula '3. upload do arquivo' primeiro.")
else:
    print(f"(feature b) processando '{input_filepath}' com unstructured (strategy='auto')...")

    # strategy='auto' decide a melhor forma de extração
    # (incluindo ocr se necessário, graças ao tesseract que instalamos)
    elements = partition(filename=input_filepath, strategy="auto")

    # 1. separa o texto comum
    text_elements = [el for el in elements if not isinstance(el, Table)]
    full_text = "\n\n".join([str(el) for el in text_elements])

    if full_text:
        print("(feature b) --- início do texto extraído (amostra) ---")
        print(full_text[:1500] + "...")
        print("(feature b) --- fim da amostra ---\n")

        # salva o texto em .txt e oferece download
        text_output_path = "texto_extraido_unstructured.txt"
        with open(text_output_path, 'w', encoding='utf-8') as f:
            f.write(full_text)
        print(f"(feature b) texto completo salvo em '{text_output_path}'.")
        files.download(text_output_path)
    else:
        print("(feature b) nenhum texto comum foi extraído.")

    # 2. separa as tabelas
    table_elements = [el for el in elements if isinstance(el, Table)]

    if not table_elements:
        print("\n(feature b) unstructured não encontrou tabelas neste documento.")
    else:
        print(f"\n(feature b) encontradas {len(table_elements)} tabelas!")

        excel_path_uns = 'tabelas_extraidas_unstructured.xlsx'

        # aqui processamos os dataframes primeiro
        dataframes_extraidos = []
        for i, table_el in enumerate(table_elements):
            display(Markdown(f"**tabela {i+1} (unstructured)**"))
            try:
                # unstructured extrai tabelas como html. nós convertemos para dataframe.
                table_html = table_el.metadata.text_as_html
                # pd.read_html retorna uma *lista* de dataframes
                table_df = pd.read_html(io.StringIO(table_html))[0]
                dataframes_extraidos.append(table_df)
                display(table_df)
            except Exception as e:
                print(f"(feature b) erro ao converter tabela {i+1}: {e}")
                # às vezes, o html é a melhor visualização
                display(HTML(table_html))

        # agora salvamos, com base na escolha do usuário
        if salvar_em_uma_aba:
            print("(feature b) salvando todas as tabelas em uma única aba ('todas_tabelas')...")
            with pd.ExcelWriter(excel_path_uns) as writer:
                current_row = 0
                for i, table_df in enumerate(dataframes_extraidos):
                    # escreve o nome da tabela
                    pd.DataFrame([f"tabela {i+1}"]).to_excel(writer, sheet_name='todas_tabelas', startrow=current_row, index=False, header=False)
                    current_row += 1
                    # escreve a tabela
                    table_df.to_excel(writer, sheet_name='todas_tabelas', startrow=current_row, index=False)
                    current_row += len(table_df) + 2 # +2 para uma linha de espaço
        else:
            print("(feature b) salvando cada tabela em uma aba separada...")
            with pd.ExcelWriter(excel_path_uns) as writer:
                for i, table_df in enumerate(dataframes_extraidos):
                    table_df.to_excel(writer, sheet_name=f'tabela_{i+1}', index=False)

        print(f"\n(feature b) todas as tabelas foram salvas em '{excel_path_uns}'.")
        files.download(excel_path_uns)

"""---

##extração com empilhamento

esta feature usa `pdfplumber` para "empilhar" tabelas que são continuações umas das outras. o resultado é salvo em **uma única aba**.
"""

# funções de ajuda da feature c

def clean_cell_c(cell_value):
    """
    limpa o lixo de uma célula extraída pelo pdfplumber.
    (remove espaços em branco e os pontos extras no início/fim)
    """
    if cell_value is None:
        return None

    # remove espaços e os pontos extras
    cleaned = str(cell_value).strip().strip('.')

    # se a célula era apenas um '.' ou ' ', retorna none
    if cleaned == "":
        return None
    return cleaned


def extract_and_stack_tables(filepath, output_path):
    """
    extrai todas as tabelas, limpa-as e empilha (concatena)
    aquelas que parecem ser parte da mesma tabela lógica.
    """
    print(f"(feature c) processando e empilhando tabelas de: {filepath}...")

    all_data_rows = []
    master_header = None
    header_col_count = 0

    with pdfplumber.open(filepath) as pdf:

        for i, page in enumerate(pdf.pages):
            # extrai todas as tabelas da página
            tables = page.extract_tables()

            for j, table_data in enumerate(tables):
                if not table_data:
                    continue # pula se a tabela estiver vazia

                # --- 1. limpeza (corrige os 'pontos extras') ---
                cleaned_table = []
                for row in table_data:
                    cleaned_row = [clean_cell_c(cell) for cell in row]
                    # adiciona a linha só se ela não ficou completamente vazia
                    if any(cleaned_row):
                        cleaned_table.append(cleaned_row)

                if not cleaned_table:
                    continue # pula se a tabela limpa estiver vazia

                # --- 2. empilhamento (corrige as 'milhares de abas') ---

                # se o cabeçalho mestre ainda não foi definido, use esta tabela
                if master_header is None:
                    master_header = cleaned_table[0]
                    header_col_count = len(master_header)
                    all_data_rows.extend(cleaned_table[1:]) # adiciona os dados
                    print(f"(feature c) cabeçalho mestre definido (p{i+1}_t{j+1}) com {header_col_count} colunas.")

                # se já temos um cabeçalho, verifique se esta tabela é uma continuação
                else:
                    # se a primeira linha desta tabela não é o cabeçalho,
                    # mas a contagem de colunas bate, assuma que é dados.
                    if cleaned_table[0] != master_header and len(cleaned_table[0]) == header_col_count:
                        all_data_rows.extend(cleaned_table) # adiciona todas as linhas

                    # se o cabeçalho for repetido, adicione apenas os dados
                    elif cleaned_table[0] == master_header:
                        all_data_rows.extend(cleaned_table[1:])

                    else:
                        print(f"  -> (feature c) ignorando tabela p{i+1}_t{j+1} (cabeçalho/colunas incompatíveis)")

    if not all_data_rows or master_header is None:
        print("(feature c) nenhum dado de tabela foi encontrado ou o cabeçalho não foi definido.")
        return 0

    print(f"(feature c) concatenando {len(all_data_rows)} linhas de dados em uma única tabela...")

    # cria o dataframe final com todas as linhas e o cabeçalho mestre
    final_df = pd.DataFrame(all_data_rows, columns=master_header)

    # remove quaisquer linhas que possam estar totalmente vazias
    final_df.dropna(how='all', inplace=True)

    print(f"(feature c) dataframe final criado com {len(final_df)} linhas.")

    # salva em uma única aba
    # o engine 'openpyxl' salva em utf-8 por padrão, o excel vai ler corretamente.
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        final_df.to_excel(writer, sheet_name="tabelas_empilhadas", index=False)

    return len(final_df)

"""### execução (feature c)"""

if 'input_filepath' not in locals() or not os.path.exists(input_filepath):
    print("erro: faça o upload de um arquivo na célula '3. upload do arquivo' primeiro.")
elif not input_filepath.lower().endswith('.pdf'):
    print(f"a feature c (pdfplumber) funciona apenas com pdfs. pulando arquivo: {input_filepath}")
else:
    output_file_c = "tabelas_empilhadas_pdfplumber.xlsx"

    try:
        # 1. extrair, limpar e empilhar
        total_linhas = extract_and_stack_tables(input_filepath, output_file_c)

        print(f"\n--- (feature c) sucesso ---")
        print(f"extração e limpeza concluídas.")
        print(f"{total_linhas} linhas salvas em uma única aba.")
        print(f"baixando resultado: {output_file_c}")

        # 4. fazer o download do arquivo final
        files.download(output_file_c)

    except Exception as e:
        print(f"\n--- (feature c) erro inesperado ---")
        print(f"ocorreu uma falha durante a extração:")
        print(e)
